---

- name: Install libmagickwand
  apt: name=libmagickwand-6.q16-2 state=present update_cache=yes cache_valid_time=3600
  become: yes
  when: ansible_distribution == 'Debian'

- name: Install libmagickwand
  apt: name=libmagickwand5 state=present update_cache=yes cache_valid_time=3600
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Fetch imagick .deb
  get_url: url=https://ftp.weheartwebsites.de/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/php5-imagick_{{ php5fpm_ext_imagick_version }}_amd64.deb dest=/tmp/php5-imagick_{{ php5fpm_ext_imagick_version }}_amd64.deb validate_certs=false

- name: Install imagick .deb
  apt: deb=/tmp/php5-imagick_{{ php5fpm_ext_imagick_version }}_amd64.deb
  become: yes

- name: Apt hold
  shell: echo "php5-imagick hold" | dpkg --set-selections
  become: yes
