---

- name: install dependencies
  include_tasks: packages-{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}.yml

- name: Get php-fpm version
  command: /usr/sbin/php-fpm --version
  register: php5fpm_current
  ignore_errors: yes

- import_tasks: php-fpm.yml
  when: php5fpm_current | failed or not php5fpm_current.stdout | search(php5fpm_version_string_match)

- import_tasks: config.yml

- import_tasks: ext-apcu.yml

- import_tasks: ext-imagick.yml

- import_tasks: ext-igbinary.yml

- import_tasks: ext-memcached.yml

- import_tasks: ext-redis.yml

- name: Check if munin-node is installed
  command: dpkg -L munin-node
  register: dpkg_munin_node_check
  ignore_errors: yes

- name: Configure munin plugin
  import_tasks: munin-plugin.yml
  when: dpkg_munin_node_check.rc == 0
