---

- name: install .deb
  apt:
    deb: https://ftp.weheartwebsites.de/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/php5-fpm_{{ php5fpm_version }}_amd64.deb
  become: yes
  notify: restart_php5_fpm
